// Package web embeds the dashboard. static/app.js is generated by `make web`.
package web

import (
	"embed"
	"io/fs"
)

//go:embed static
var embedded embed.FS

// Static is the dashboard's document root.
var Static, _ = fs.Sub(embedded, "static")
